dat<- read.table("household_power_consumption.txt", header=TRUE, sep = ";")
data<- subset(dat, Date=="1/2/2007" | Date=="2/2/2007")
plot(1:2880,as.numeric(as.character(data$Global_active_power)),type="n",axes=F,xlab="",ylab="Global Active Power (kilowatts)")
box()
lines(1:2880,as.numeric(as.character(data$Global_active_power)))
axis(2)
axis(1,at=c(1,1440,2880),labels=c("Thu","Fri","Sat"))
dev.copy(png, "plot2.png")
dev.off()