dat<- read.table("household_power_consumption.txt", header=TRUE, sep = ";")
data<- subset(dat, Date=="1/2/2007" | Date=="2/2/2007")
hist(as.numeric(as.character(data$Global_active_power)), col="red", main="Global Active Power", xlab = "Global Active Power (kilowatts)", ylab = "Frequency")
dev.copy(png, "plot1.png")
dev.off()