dat<- read.table("household_power_consumption.txt", header=TRUE, sep = ";")
data<- subset(dat, Date=="1/2/2007" | Date=="2/2/2007")
with(data, plot(1:2880, Sub_metering_1,type="n", axes=FALSE, ylab="Energy sub metering", xlab=""))
box()
with(data,lines(1:2880, as.numeric(as.character(Sub_metering_1))))
with(data,lines(1:2880, as.numeric(as.character(Sub_metering_2)),col="red"))
with(data,lines(1:2880, as.numeric(as.character(Sub_metering_3)),col="blue"))
axis(2)
axis(1,at=c(1,1440,2880),labels=c("Thu","Fri","Sat"))
legend("topright", lty="solid", col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex=0.5)
dev.copy(png, "plot3.png")
dev.off()